name: Canary Testing for Bindings and Packages
on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - "**"
jobs:
  build-and-test:
    name: build-and-test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        ocaml-version:
        - "5"
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - uses: ./.github/actions/canary-test-setup
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Configure with CMake
      env:
        CC: ${{ matrix.os == 'macos-latest' && 'ccache clang' || 'ccache gcc' }}
        CXX: ${{ matrix.os == 'macos-latest' && 'ccache clang++' || 'ccache g++' }}
      run: "mkdir -p build\ncd build\neval $(opam env)\ncmake .. \\\n  -G Ninja \\\n
        \  \\\n  -DZ3_BUILD_LIBZ3_SHARED=ON \\\n  -DZ3_BUILD_OCAML_BINDINGS=ON \\\n
        \ -DZ3_BUILD_JAVA_BINDINGS=OFF \\\n  -DZ3_BUILD_PYTHON_BINDINGS=OFF \\\n  -DZ3_BUILD_EXECUTABLE=OFF
        \\\n  -DZ3_BUILD_TEST_EXECUTABLES=OFF \\\n  -DCMAKE_VERBOSE_MAKEFILE=TRUE
        \n"
    - name: Build Z3 and OCaml bindings
      run: "eval $(opam env)\n  cd build\n  ninja build_z3_ocaml_bindings \n"
    - name: Compile ml_example.byte
      run: |
        eval $(opam env)
        ocamlfind ocamlc -o ml_example.byte \
          -package zarith \
          -linkpkg \
          -I build/src/api/ml \
          -dllpath build/src/api/ml \
          build/src/api/ml/z3ml.cma \
          examples/ml/ml_example.ml
    - name: Run ml_example.byte
      run: |
        eval $(opam env)
        # only macOS need this fix
        export DYLD_LIBRARY_PATH=$(pwd)/build
        ocamlrun ./ml_example.byte
    - name: Compile ml_example (native)
      run: |
        eval $(opam env)
        ocamlfind ocamlopt -o ml_example \
          -package zarith \
          -linkpkg \
          -I build/src/api/ml \
          build/src/api/ml/z3ml.cmxa \
          examples/ml/ml_example.ml
    - name: Run ml_example (native)
      run: |
        export DYLD_LIBRARY_PATH=$(pwd)/build
        ./ml_example
  packaging:
    name: packaging (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        ocaml-version:
        - "5"
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - uses: ./.github/actions/canary-test-setup
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Install package
      run: |
        eval $(opam env)
        opam repo add my-opam-fork "git+https://github.com/arbipher/opam-repository.git#add-z3-dev"
        opam install -y z3.dev --verbose
    - name: Compile ml_example_with_pkg.byte
      run: |
        eval $(opam env)
        ocamlfind ocamlc -package z3 -linkpkg -o ml_example_with_pkg.byte ml_example.ml
    - name: Run ml_example_with_pkg.byte
      run: |
        eval $(opam env)
        ocamlrun ./ml_example_with_pkg.byte
    - name: Compile ml_example_with_pkg (native)
      run: |
        eval $(opam env)
        ocamlfind ocamlopt -package z3 -linkpkg -o ml_example_with_pkg ml_example.ml
    - name: Run ml_example_with_pkg (native)
      run: ./ml_example
